name: instrument-and-harden-image

# Only trigger, when the build workflow succeeded
on:
  workflow_run:
    workflows: ["build-image"]
    types:
      - completed

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Curl and build Slim SaaS CLI
        shell: bash
        run: |
          curl https://platform.zero.dev.saas.getslim.ai/.service/releases/slim/0.0.7-dev | sh
          ~/.slim/bin/slim config gen --save --token ${{ secrets.SLIM_TOKEN }}
      -
        name: Instrument the image
        shell: bash
        run: |
          ~/.slim/bin/slim --debug instrument \
          --stop-grace-period 999s  \
          ghcr.io/mritunjaysharma394/node-app:latest
      -
        name: Run the Initial Image
        shell: bash
        run: |
          docker run -d --rm \
          --user root \
          --cap-add ALL \
          -p 8088:80 \
          --name app-instrumented ghcr.io/mritunjaysharma394/node-app:latest-slim-instrumented      
      -
        name: Probe the container
        shell: bash
        run: |
          curl localhost:8088
      -
        name: Stop the instrumented container
        shell: bash
        run: |
          docker stop -t 999 app-instrumented
      -
        name: Harden the instrumented container
        shell: bash
        run: |
          ~/.slim/bin/slim harden --instrumented-image ghcr.io/mritunjaysharma394/node-app:latest-slim-instrumented
      -
        name: Test the Hardened Image
        shell: bash
        run: |
          docker run -d --rm \
          --user root \
          --cap-add ALL \
          -p 8089:80 \
          --name app-hardened ghcr.io/mritunjaysharma394/node-app:latest-slim-hardened
      -
        name: Probe the hardened container
        shell: bash
        run: |
          curl localhost:8089
      -
        name: Stop the hardened container
        shell: bash
        run: |
          docker stop app-hardened
  